version: "2"
services:
  app:
    container_name: graphqlapp
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: graphqlmongo
    image: mongo
    volumes:
      # - ./data:/data/db Para Linux
      - data:/data/db #Para Windows
    ports:
      - "27017:27017"
  admin-mongo:
    image: 0x59/admin-mongo:latest
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - CONN_NAME=mongo
      - DB_HOST=mongo
    links:
      - mongo
volumes: 
  data: